server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.149.103:3306/zohar_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zohar
    password: asd123000
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 28740000
      connection-test-query: SELECT 1
